### PR TITLE
Refactor game files into a `game` directory.

### LINKED ISSUE #36: Refactor project structure
gonna organize project files into some `game` directory

### PR DESCRIPTION
**Pull request by SavagePastaMan**
This is to clean up the main directory.

Closes #36

### CODE REVIEW

**Review by GDWR — DISMISSED** [review]
LGTM

**Comment by SavagePastaMan** [comment]
> Put Main.py in root
no, putting `__main__.py` in `game` lets you run `game` as a module, i.e. `python game`.

> also relative imports are wrong
runs fine on my machine, i have no reason to think they are incorrect. what error did you get?

**Comment by GDWR** [comment]
> 
> 
> > Put Main.py in root
> 
> no, putting `__main__.py` in `game` lets you run `game` as a module, i.e. `python game`.
> 
If you feel that would be better sure, I'm just used to seeing most projects having their entrypoint in the root.

> > also relative imports are wrong
> 
> runs fine on my machine, i have no reason to think they are incorrect. what error did you get?
This is because I was running it from the `__main__,py` making the `CWD` inside Game so `game/` was not there relatively.

**Comment by SavagePastaMan** [comment]
so...all good?

**Review by GDWR — APPROVED** [review]
:godmode:  all god

**Pull request merged**
