### PR TITLE
Add ability to change volume

### PR DESCRIPTION
**Pull request by EwwPhysics**
Linked config to music player. I think it works, not 100% sure since I wasn't able to change the settings mid-game.

### CODE REVIEW

**Review by SavagePastaMan — CHANGES_REQUESTED** [review]
volume doesn't update if the setting is changed from the pause menu. likewise with the on/off

**Comment by EwwPhysics** [comment]
> volume doesn't update if the setting is changed from the pause menu. likewise with the on/off

Can you merge this because I'm unable to change from the pause menu as of now. Then I can rebase from master in my branch where I'm working on the pause thing and fix it there. please and thank you

**Comment by EwwPhysics** [comment]
> > volume doesn't update if the setting is changed from the pause menu. likewise with the on/off
> 
> Can you merge this because I'm unable to change from the pause menu as of now. Then I can rebase from master in my branch where I'm working on the pause thing and fix it there. please and thank you

Ah wait, I think I created the pause branch from this one, not master, so you shouldn't need to merge it (I think). Don't delete the PR though just in case

**Comment by EwwPhysics** [comment]
You were wrong about the pause thing (I think) >:(

**Pull request closed without merging**
